spring:
  application:
    name: gatling-service
  datasource:
    datasource:
        url: jdbc:h2:mem:gatling;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver
        platform: h2
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  h2:
    console:
      enabled: true
      path: /console
            
server:
  port: 8090